export const SEQUELIZE = 'SEQUELIZE';
export const DATABASE_REQUEST = 'DATABASE_REQUEST';
export const USERS_SERVICE = 'USERS_SERVICE';
export const MESSAGES_SERVICE = 'MESSAGES_SERVICE';
export const MAILS_SERVICE = 'MAILS_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
